config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  # delete "posts/:id", to: "posts#destroy", as: :delete
  resources :posts
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :line_items, inverse_of: :order
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "lynn.desouza@alumni.uct.ac.za",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  validates :title, :content, :category_id, presence: true
  mount_uploader :image, ImageUploader
end


# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
#   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      # redirect_to root_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @posts = Post.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.order("created_at desc").limit(4).offset(1)
  end

  def new
    @post = Post.new
  end

  # def create
  #   @post = Post.new(post_params)
  #   if @post.save
  #     redirect_to @post, notice: "The post was created!"
  #   else
  #     render 'new'
  #   end
  # end

  def edit
  end

  # def update
  #   if @post.update(post_params)
  #     redirect_to @post, notice: "Update successful!"
  #   else
  #     render 'edit'
  #   end
  # end

  # def destroy
  #   @post.destroy
  #   redirect_to posts_path, notice: "Post destroyed!"
  # end

  private

  def post_params
    params.require(:post).permit!(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<section class="fdb-block bg-dark" id="thank-you-block">
  <div class="container align-items-end justify-content-start d-flex">
    <div class="row justify-content-start text-center">
      <div class="col-12 col-lg-8 col-md-8 pt-lg-5 mt-lg-5 col-sm-6">
        <p id="thank-you-message">Thanks for your enquiry! <br><br> We'll get back to you as soon as possible.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/contacts/new.html.erb
<section class="fdb-block" id="banner-contact">
  <div class="container align-items-center justify-content-end">
    <div class="row justify-content-end text-center">
      <div class="col-12 col-md-10 col-lg-12">
        <h1 class="text-right">Contact LINC</h1>
      </div>
    </div>
  </div>
</section>

<section class="fdb-block">
  <div class="container">
    <div class="row text-center justify-content-center">
      <div class="col-12 col-md-8 col-lg-8">
        <h1>Contact Us</h1>
        <p>The team welcomes you to contact us with your comments and questions. If you are a LINC user and have suggestions or features requests please feel free to make recommendations here.<br><br>
        We are also always looking to talk with like-minded people or possible collaborators. If you are working with Neural networks and perception problems, can code in php, Ruby or Python, or are doing lion research/conservation yourself please contact us here.</p>
      </div>
    </div>

    <div class="row pt-4">
      <div class="col-12 col-md-6">
        <img class="img-fluid" src="https://res.cloudinary.com/lynn-de-souza/image/upload/v1556462900/LINC%20website/Contact/contact_us_BOX.jpg">
      </div>

      <div class="col-12 col-md-6">
          <%= form_for @contact do |f| %>
          <% if flash[:error].present? %>
              <p> flash[:error]</p>
          <% end %>

          <div class="row">
            <div class="col">
              <%= f.label "Your name" %> <br>
              <%= f.text_field :name, required: true %>
            </div>
          </div>

          <div class="row mt-4">
            <div class="col">
              <%= f.label "Your email address" %> <br>
              <%= f.text_field :email, required: true %>
            </div>
          </div>

          <div class="row mt-4">
            <div class="col">
              <%= f.label "How can we help you?" %> <br>
              <%= f.text_area :message, as: :text %>
            </div>
          </div>

          <div class="hidden">
            <%= f.label :nickname %> <br>
            <%= f.text_field :nickname, hint: 'leave this field blank' %>
          </div>

          <div class="row mt-4">
            <div class="col justify-content-end">
              <%= f.submit 'Send Message', class: "btn btn-linc" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>LINC</title>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"> -->

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/1.0.2/css/froala_blocks.min.css">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
  </body>
</html>

app/views/pages/about/theteam.html.erb
<section class="fdb-block" id="banner-team" style="background-image: url(https://res.cloudinary.com/lynn-de-souza/image/upload/v1556462321/LINC%20website/Team/MEET_THE_TEAM.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <h1 class="text-right">Meet the Team</h1>
      </div>
    </div>
  </div>
</section>

<!-- Meet the team -->
<section class="fdb-block">
  <div class="container">
    <div class="row text-center justify-content-center">
      <div class="col-8">
        <h1>Collaborators</h1>
        <p>
          LINC is composed of a strong coalition of conservationists, researchers, developers, and funders. <%= link_to 'IEF R&D', "http://iefrd.com", target: "_blank", class: '' %> and <%= link_to 'Lion Guardians', "http://lionguardians.org/", target: "_blank", class: '' %> have spearheaded the development and financial aspects of LINC, but it has taken input from all the below organizations and individuals to make LINC a reality. Thank you!
        </p>
      </div>
    </div>

    <div class="row-50"></div>

    <div class="row text-center justify-content-center">
      <div class="col-sm-3 m-sm-auto">
        <%= link_to "http://www.kws.go.ke/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1556643923/LINC%20website/Team/KWS-100414-THUMB_1.jpg", class: 'img-logo', id: 'kws-logo') %>
        <% end %>
        <p style="margin-top:10px;"><em>Nation wide - Kenya</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "http://lionguardians.org/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/Lion_Guardians_logo.png", class: 'img-logo', id: 'lionguardians-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>Amboseli - Tsavo ecosystem – Kenya</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "http://www.marapredatorconservation.org/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/Mara_PCP_logo.jpg", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>The Greater Mara ecosystem - Kenya</em></p>
      </div>
    </div>

    <div class="row-50"></div>

    <div class="row text-center justify-content-center">
      <div class="col-sm-3 m-sm-auto">
        <%= link_to "https://kopelion.org/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/KopeLion_logo.png", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>Ngorongoro conservation area - Tanzania</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "http://soralo.org/rebuilding-pride/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347117/LINC%20website/Team/RTP_logo.png", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>The South Rift - Kenya</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "http://www.soysambuconservancy.org/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/Soysambu_Conservancy.png", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>Soysambu Conservancy - Kenya</em></p>
      </div>
    </div>

    <div class="row-50"></div>

    <div class="row text-center justify-content-center">
      <div class="col-sm-3 m-sm-auto">
        <%= link_to "https://www.bornfree.org.uk/kenya", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/Born_Free_logo.png", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>Meru-kora ecosystem - Kenya</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "https://www.lionlandscapes.org/", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347116/LINC%20website/Team/Lion_Lanscapes.png", class: 'img-logo') %>
        <% end %>
        <p style="margin-top:15px;"><em>Laikipia-Samburu ecosystem - Kenya</em></p>
      </div>

      <div class="col-sm-3 m-sm-auto">
        <%= link_to "", target: "_blank" do %>
          <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1556646851/LINC%20website/Team/UniversiteitLeidenLogo.svg.png", class: 'img-special') %>
        <% end %>
        <p style="margin-top:15px;"><em>Nairobi, Nakuru, Amboseli and Meru National Parks - Kenya</em></p>
      </div>
    </div>
  </div>
</section>

<section class="fdb-block">
  <div class="container">
    <div class="row text-center justify-content-center">
      <div class="col-8 text-center">
        <h1>Supporters</h1>
        <p>Since its inception, LINC has been made possible by the generous support of individual donors, foundations and Microsoft's A.I. for Earth Program.</p>
      </div>
    </div>
    <div class="row justify-content-center mb-5">
      <div class="col-3">
        <!-- <img alt="image" class="img-fluid" src="https://res.cloudinary.com/lynn-de-souza/image/upload/v1554377818/LINC%20website/Team/Microsoft-logo-768x195.png"> -->
      </div>
    </div>
  </div>
  </div>
</section>

app/views/pages/donate.html.erb
<div class="wrapper">

  <div class="sidepic">
  </div>

  <div class="main">
    <h1 id="support-header"> SUPPORT US AND HELP SAVE THE LIONS</h1>
    <p id="support-para">
      LINC has become a reality thanks to the generous support and efforts of many individuals and foundations. Thank you for enabling us to revolutionize broad scale lion conservation!
      <br><br>
      The sky is now the limit. We need your support to make LINC as impactful and broad-scale as possible - please consider donating funds and/or expertise to unite conservationists and developers and begin to save lions across their range.
    </p>
      <p id="support-buttons" class="mx-auto mt-4 mb-4">
        <%= link_to 'Support with Funds', "#funds", class: 'btn-linc mr-3 text-center' %>
         <%= link_to 'Support the Tech', "#tech", class: 'btn-linc ml-3 text-center' %>
      </p>

      <div class="support-with-funds">
        <h4 id="funds">SUPPORT WITH FUNDS</h4>
         <p><br>You can support LINC through our U.S. fiscal sponsor, Wildlife Guardians.
          <br>
          <span style="font-size: 12px;">* Wildlife Guardians is a 501(c)3 not-for-profit organization so your contribution will be tax deductible to the fullest extent allowable by U.S. law. One hundred percent of your donation will support direct LINC activities because Wildlife Guardians does not charge a fee or deduct any administrative expenses.</span></p>

          <p>
            Ways to donate:
            <ul style="list-style-type:none;">
              <li><%= link_to 'Credit Card', "https://secure.acceptiva.com/?cst=3bbd26", target: "_blank" %></li>

              <br>

              <li>PayPal:
                <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                <input type="hidden" name="cmd" value="_donations" />
                <input type="hidden" name="business" value="info@linclion.org" />
                <input type="hidden" name="currency_code" value="USD" />
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                <img alt="" border="0" src="https://www.paypal.com/en_KE/i/scr/pixel.gif" width="1" height="1" />
              </form></p>
              </li>
              <br>

              <li>Cheque: please print <%= link_to 'this form', "http://www.lionguardiansus.org/LGUS_donationform.pdf", target: "_blank" %> and mail it with a cheque payable to Lion Guardians U.S.</li>
            </ul>
          </p>
        </div>

        <div class="support-the-tech">
          <h4 id="tech"> SUPPORT THE TECH</h4>
           <p>Join us.<br> <br> We are always looking to work with like minded people and possible collaborators. If you are working with Neural networks and perception problems, can code in PHP, Ruby or Python, or are working with lions yourself and would like to help, please <%= link_to 'contact us.', new_contact_path, class: '' %> </p>
        </div>
  </div>
</div>

<div class="container" id="support-mobile">
    <h1 id="support-header"> SUPPORT US AND HELP SAVE THE LIONS</h1>
    <p id="support-para">
      The development of LINC has been made possible thanks to the generous support of many individuals and foundations. We would like to thank you for enabling us to revolutionize broad scale lion conservation. It takes a community to conserve lions.
    </p>
      <p id="support-buttons" class="mx-auto mt-4 mb-4">
        <%= link_to 'Support with Funds', "#funds-mobile", class: 'btn-linc mr-3 text-center' %>
         <%= link_to 'Support the Tech', "#tech-mobile", class: 'btn-linc ml-3 text-center' %>
      </p>

      <div class="support-with-funds">
        <h4 id="funds-mobile">SUPPORT WITH FUNDS</h4>
         <p><br>You can support LINC through our U.S. fiscal sponsor, Wildlife Guardians.
          <br>
          <span style="font-size: 12px;">* Wildlife Guardians is a 501(c)3 not-for-profit organization so your contribution will be tax deductible to the fullest extent allowable by U.S. law. One hundred percent of your donation will support direct LINC activities because Wildlife Guardians does not charge a fee or deduct any administrative expenses.</span></p>

          <p>
            Ways to donate:
            <li><%= link_to 'Credit Card', "https://secure.acceptiva.com/?cst=3bbd26", target: "_blank" %></li>
            <li>PayPal</li>
            <li><%= link_to 'Credit Card', "https://secure.acceptiva.com/?cst=3bbd26", target: "_blank" %></li>

          </p>
        </div>

        <div class="support-the-tech">
          <h4 id="tech-mobile"> SUPPORT THE TECH</h4>
           <p>Join us.<br> <br> We are always looking to work with like minded people or possible collaborators. If you are working with Neural networks and perception problems, can code in php, Ruby or python, or are working with lions yourself and would like to help, please <%= link_to 'contact us.', new_contact_path, class: '' %> </p>
        </div>
  </div>

app/views/posts/show.html.erb
<!-- <h1><%= @post.title %></h1>
<article class=”post”>
 <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-responsive" %>
  <p><%= @post.content %></p>

</article> -->

<div class="container post-container">

    <!-- Portfolio Item Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%= @post.title %>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-responsive" %>
        </div>

        <div class="col-md-4">
            <h3>Project Description</h3>
            <p><%= @post.content %></p>
        </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <div class="row">

        <div class="col-lg-12">
            <h3 class="page-header">Related Projects</h3>
        </div>

        <% @posts.each do |post| %>
            <div class="col-sm-3 col-xs-6">
                <%= link_to post_path(post) do %>
                  <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-responsive" %>
                <% end %>
            </div>
        <% end %>

    </div>
    <!-- /.row -->
</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_banner.html.erb
<div class="banner">
    <h1 id="hero-text">
      Connecting Lions.
      <br>
      Connecting Researchers.
      <br>
      Changing Conservation.
    </h1>
</div>

app/views/shared/_footer.html.erb
<footer class="fdb-block footer-small bg-dark pb-5">
  <div class="container">
    <div class="row text-center align-items-center">
      <div class="col-12 col-lg-2 text-lg-left">
        <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347093/LINC%20website/Home/logo.png") %>
      </div>

      <div class="col mt-4 mt-lg-0 text-center">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', page_path('about/linc'), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', new_contact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Privacy Policy', page_path('about/userpolicy'), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Terms of Service', page_path('about/termsofservice'), class: 'nav-link' %>
          </li>
        </ul>
      </div>

      <div class="col-12 col-lg-2 mt-4 mt-lg-0 text-lg-right linc-orange">
        <!-- <a href="#" class="mx-2"><i class="fab fa-twitter" aria-hidden="true"></i></a>
        <a href="#" class="mx-2"><i class="fab fa-facebook" aria-hidden="true"></i></a>
        <a href="#" class="mx-2"><i class="fab fa-instagram" aria-hidden="true"></i></a> -->
      </div>
    </div>

    <div class="row mt-4">
      <div style="font-size: 11px;" class="col text-center linc-grey">
        All website content ©LINC and may not be used without permission
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<% Category.all.each do |category| %>
  <li>
  <%= link_to category.name, posts_path(category: category.name) %>
  </li>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md fixed-top" id="navbar-main">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 navbarToggler01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Join LINC', "https://linc.linclion.org", target: "_blank", class: 'nav-link navbar-join-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'LINC login', "https://linc.linclion.org", target: "_blank", class: 'nav-link navbar-join-link' %>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
      <%= link_to root_path, class: "navbar-brand mx-auto" do %>
        <%= image_tag("https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347093/LINC%20website/Home/logo.png") %>
      <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbarToggler01">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 navbarToggler01">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to page_path('donate'), class: "nav-link", id:"donate" do %>
                 SUPPORT
              <% end %>
            </li>
        </ul>
    </div>
</nav>



<nav id="navbar-secondary" class="navbar navbar-expand-sm fixed-top fixed-top-2">
    <div class="mx-auto d-sm-flex d-block flex-sm-nowrap">
        <div class="text-center navbar-collapse collapse dual-collapse2">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'Home', root_path, class: 'nav-link navbar-linc-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'About LINC', page_path('about/linc'), class: 'nav-link navbar-linc-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Meet the Team', page_path('about/theteam'), class: 'nav-link navbar-linc-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact LINC', new_contact_path, class: 'nav-link navbar-linc-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Force for Change', page_path('about/campaign'), class: 'nav-link navbar-linc-link' %>
                </li>
               <!--  <li class="nav-item">
                    <%= link_to 'Our Blog', posts_path, class: 'nav-link navbar-linc-link' %>
                </li> -->
            </ul>
        </div>
    </div>
</nav>



  <div class="container">
    <nav class="navbar d-block d-sm-none">
      <a class="navbar-brand" href="">
        <img src="https://res.cloudinary.com/lynn-de-souza/image/upload/v1548347093/LINC%20website/Home/logo.png" height="30" alt="image">
      </a>

      <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNav3" aria-controls="navbarNav3" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav3">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link navbar-linc-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'About LINC', page_path('about/linc'), class: 'nav-link navbar-linc-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Meet the Team', page_path('about/theteam'), class: 'nav-link navbar-linc-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Contact LINC', new_contact_path, class: 'nav-link navbar-linc-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Force for Change', page_path('about/campaign'), class: 'nav-link navbar-linc-link', id: "Force" %>
          </li>
        </ul>
        <div class="text-right">
            <%= link_to page_path('donate'), class: "btn btn-outline-none nav-link", id:"donate" do %>
                 SUPPORT
              <% end %>
        </div>
      </div>
    </nav>
  </div>